/* Generated by re2swift */
// re2swift $INPUT -o $OUTPUT -i -d

func lex(_ string: UnsafeBufferPointer<UInt8>) -> Bool {
  var cursor = 0, marker = 0
  var yych: UInt8 = 0

  let yypeek    = { string[cursor] }
  let yyskip    = { cursor += 1 }
  let yybackup  = { marker = cursor }
  let yyrestore = { cursor = marker }
  let yydebug   = { print("lex: char '\(UnicodeScalar(yych))'") }

  
  var yystate: UInt = 0
  yyl: while true {
    switch yystate {
      case 0:
        yydebug()
        yych = yypeek()
        yyskip()
        switch yych {
          case 0x41...0x5A:
            fallthrough
          case 0x61...0x7A:
            yystate = 3
            continue yyl
          default:
            yystate = 1
            continue yyl
        }
      case 1:
        yydebug()
        yystate = 2
        continue yyl
      case 2:
        yydebug()
        return false
      case 3:
        yydebug()
        yybackup()
        yych = yypeek()
        switch yych {
          case 0x30...0x39:
            yyskip()
            yystate = 4
            continue yyl
          default:
            yystate = 2
            continue yyl
        }
      case 4:
        yydebug()
        yych = yypeek()
        switch yych {
          case 0x41...0x5A:
            fallthrough
          case 0x61...0x7A:
            yyskip()
            yystate = 6
            continue yyl
          default:
            yystate = 5
            continue yyl
        }
      case 5:
        yydebug()
        yyrestore()
        yystate = 2
        continue yyl
      case 6:
        yydebug()
        yych = yypeek()
        switch yych {
          case 0x30...0x39:
            yyskip()
            yystate = 7
            continue yyl
          default:
            yystate = 5
            continue yyl
        }
      case 7:
        yydebug()
        yych = yypeek()
        switch yych {
          case 0x3B:
            yyskip()
            yystate = 8
            continue yyl
          default:
            yystate = 5
            continue yyl
        }
      case 8:
        yydebug()
        yych = yypeek()
        switch yych {
          case 0x20:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x61...0x7A:
            yyskip()
            yystate = 9
            continue yyl
          default:
            yystate = 5
            continue yyl
        }
      case 9:
        yydebug()
        yych = yypeek()
        switch yych {
          case 0x20:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x61...0x7A:
            yyskip()
            yystate = 9
            continue yyl
          default:
            yystate = 10
            continue yyl
        }
      case 10:
        yydebug()
        return true
      default: fatalError("internal lexer error")
    }
  }

}

@main struct Program {
  static func main() {
    let test: StaticString = "e1m1;Hanger\0"
    test.withUTF8Buffer {
      assert(lex($0))
    }
  }
}
