/* Generated by re2swift */
#sourceLocation(file: "advanced.re", line: 1)
// re2swift $INPUT -o $OUTPUT -cf
import Foundation

func log(_ items: Any..., separator: String = " ", terminator: String = "\n") {
#if DEBUG
  var stderr = FileHandle.standardError
  print(items, separator: separator, terminator: terminator, to: &stderr)
#endif
}

extension FileHandle: @retroactive TextOutputStream {
  public func write(_ string: String) {
    self.write(Data(string.utf8))
  }
}

struct State {
  static let bufferSize = 4096-32-184-1
  static let tagNone = -1

  private var yylimit  = Self.bufferSize
  private var yycursor = Self.bufferSize
  private var yymarker = Self.bufferSize
  private var token    = Self.bufferSize
  private var yycond   = Self.bufferSize
  private var yystate  = -1
  private var yyaccept = -1

  private var mTagPool = [MTag]()

  
#sourceLocation(file: "advanced.swift", line: 35)
  private var yyt1 = tagNone
  private var yyt2 = tagNone
#sourceLocation(file: "advanced.re", line: 31)

  
#sourceLocation(file: "advanced.swift", line: 41)
  private weak var yytm1: MTag? = nil
  private weak var yytm10: MTag? = nil
  private weak var yytm2: MTag? = nil
  private weak var yytm3: MTag? = nil
  private weak var yytm4: MTag? = nil
  private weak var yytm5: MTag? = nil
  private weak var yytm6: MTag? = nil
  private weak var yytm7: MTag? = nil
  private weak var yytm8: MTag? = nil
  private weak var yytm9: MTag? = nil
#sourceLocation(file: "advanced.re", line: 32)


  // Buffer is zero-initialized, no need to write sentinel
  private var buffer = ContiguousArray<UInt8>(repeating: 0, count: Self.bufferSize + 1)
}

extension State {
  mutating func parse() -> Status {
    
#sourceLocation(file: "advanced.swift", line: 62)
let yycmedia_type: Int = 0
let yycheader: Int = 22
#sourceLocation(file: "advanced.re", line: 40)


    var yych: UInt8 = 0
    var l1: Int, l2: Int
    var f1: MTag? = nil, f2: MTag? = nil
    var p1: MTag? = nil, p2: MTag? = nil, p3: MTag? = nil, p4: MTag? = nil

    
#sourceLocation(file: "advanced.swift", line: 74)
  var yystate: Int = self.yystate
  yyl: while true {
    switch yystate {
      case -1...0:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yyt1 = self.yycursor
            self.yycursor += 1
            yystate = 3
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 44
              return .waiting
            }
            self.yycursor += 1
            yystate = 1
            continue yyl
        }
      case 1:
        yystate = 2
        continue yyl
      case 2:
        self.yystate = yycmedia_type
#sourceLocation(file: "advanced.re", line: 115)
        return .error
#sourceLocation(file: "advanced.swift", line: 118)
      case 3:
        self.yymarker = self.yycursor
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            yystate = 5
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 45
              return .waiting
            }
            yystate = 2
            continue yyl
        }
      case 4:
        yych = self.buffer[self.yycursor]
        yystate = 5
        continue yyl
      case 5:
        switch yych {
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yycursor += 1
            yystate = 4
            continue yyl
          case 0x2F:
            self.yycursor += 1
            yystate = 7
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 46
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 6:
        self.yycursor = self.yymarker
        yystate = 2
        continue yyl
      case 7:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x09:
            fallthrough
          case 0x0D:
            fallthrough
          case 0x20:
            fallthrough
          case 0x3B:
            if self.yylimit <= self.yycursor {
              self.yystate = 47
              return .waiting
            }
            yystate = 6
            continue yyl
          default:
            yystate = 9
            continue yyl
        }
      case 8:
        yych = self.buffer[self.yycursor]
        yystate = 9
        continue yyl
      case 9:
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yytm6 = self.yytm10
            self.yytm6 = self.add(tag: self.yytm6, value: Self.tagNone)
            self.yytm5 = self.yytm9
            self.yytm5 = self.add(tag: self.yytm5, value: Self.tagNone)
            self.yytm4 = self.yytm8
            self.yytm4 = self.add(tag: self.yytm4, value: Self.tagNone)
            self.yytm3 = self.yytm7
            self.yytm3 = self.add(tag: self.yytm3, value: Self.tagNone)
            self.yyt2 = self.yycursor
            self.yycursor += 1
            yystate = 10
            continue yyl
          case 0x0D:
            self.yytm6 = self.yytm10
            self.yytm6 = self.add(tag: self.yytm6, value: Self.tagNone)
            self.yytm5 = self.yytm9
            self.yytm5 = self.add(tag: self.yytm5, value: Self.tagNone)
            self.yytm4 = self.yytm8
            self.yytm4 = self.add(tag: self.yytm4, value: Self.tagNone)
            self.yytm3 = self.yytm7
            self.yytm3 = self.add(tag: self.yytm3, value: Self.tagNone)
            self.yyt2 = self.yycursor
            self.yycursor += 1
            yystate = 11
            continue yyl
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yycursor += 1
            yystate = 8
            continue yyl
          case 0x3B:
            self.yyt2 = self.yycursor
            self.yycursor += 1
            yystate = 12
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 48
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 10:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 10
            continue yyl
          case 0x0D:
            self.yycursor += 1
            yystate = 11
            continue yyl
          case 0x3B:
            self.yycursor += 1
            yystate = 12
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 49
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 11:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x0A:
            self.yycursor += 1
            yystate = 13
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 50
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 12:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 12
            continue yyl
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yytm7 = self.add(tag: self.yytm7, value: self.yycursor)
            self.yycursor += 1
            yystate = 14
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 51
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 13:
        l1 = self.yyt1
        l2 = self.yyt2
        p1 = self.yytm3
        p2 = self.yytm4
        p3 = self.yytm5
        p4 = self.yytm6
        self.yystate = yycmedia_type
#sourceLocation(file: "advanced.re", line: 86)
        
        print("media type: \(getString(l1..<l2))")

        var pnameStart = p1, pnameEnd = p2
        var pvalStart  = p3, pvalEnd  = p4

        while pnameStart != nil {
          log("\t\(getString(pnameStart!.elem..<pnameEnd!.elem)) = \(getString(pvalStart!.elem..<pvalEnd!.elem))")
          pnameStart = pnameStart!.prev
          pnameEnd   = pnameEnd!.prev
          pvalStart  = pvalStart!.prev
          pvalEnd    = pvalEnd!.prev
        }

        return .done

#sourceLocation(file: "advanced.swift", line: 382)
      case 14:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yycursor += 1
            yystate = 14
            continue yyl
          case 0x3D:
            self.yytm8 = self.add(tag: self.yytm8, value: self.yycursor)
            self.yycursor += 1
            yystate = 15
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 52
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 15:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yytm9 = self.add(tag: self.yytm9, value: self.yycursor)
            self.yycursor += 1
            yystate = 16
            continue yyl
          case 0x22:
            self.yytm9 = self.add(tag: self.yytm9, value: self.yycursor)
            self.yycursor += 1
            yystate = 17
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 53
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 16:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yytm10 = self.add(tag: self.yytm10, value: self.yycursor)
            self.yycursor += 1
            yystate = 18
            continue yyl
          case 0x0D:
            self.yytm3 = self.yytm7
            self.yytm4 = self.yytm8
            self.yytm5 = self.yytm9
            self.yytm6 = self.yytm10
            self.yytm6 = self.add(tag: self.yytm6, value: self.yycursor)
            self.yycursor += 1
            yystate = 11
            continue yyl
          case 0x21:
            fallthrough
          case 0x23...0x27:
            fallthrough
          case 0x2A...0x2B:
            fallthrough
          case 0x2D...0x2E:
            fallthrough
          case 0x30...0x39:
            fallthrough
          case 0x41...0x5A:
            fallthrough
          case 0x5E...0x7A:
            fallthrough
          case 0x7C:
            fallthrough
          case 0x7E:
            self.yycursor += 1
            yystate = 16
            continue yyl
          case 0x3B:
            self.yytm10 = self.add(tag: self.yytm10, value: self.yycursor)
            self.yycursor += 1
            yystate = 12
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 54
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 17:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x1F:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 55
              return .waiting
            }
            yystate = 6
            continue yyl
          case 0x22:
            self.yycursor += 1
            yystate = 19
            continue yyl
          case 0x5C:
            self.yycursor += 1
            yystate = 20
            continue yyl
          default:
            self.yycursor += 1
            yystate = 17
            continue yyl
        }
      case 18:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 18
            continue yyl
          case 0x0D:
            self.yytm3 = self.yytm7
            self.yytm4 = self.yytm8
            self.yytm5 = self.yytm9
            self.yytm6 = self.yytm10
            self.yycursor += 1
            yystate = 11
            continue yyl
          case 0x3B:
            self.yycursor += 1
            yystate = 12
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 56
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 19:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yytm10 = self.add(tag: self.yytm10, value: self.yycursor)
            self.yycursor += 1
            yystate = 18
            continue yyl
          case 0x0D:
            self.yytm3 = self.yytm7
            self.yytm4 = self.yytm8
            self.yytm5 = self.yytm9
            self.yytm6 = self.yytm10
            self.yytm6 = self.add(tag: self.yytm6, value: self.yycursor)
            self.yycursor += 1
            yystate = 11
            continue yyl
          case 0x3B:
            self.yytm10 = self.add(tag: self.yytm10, value: self.yycursor)
            self.yycursor += 1
            yystate = 12
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 57
              return .waiting
            }
            yystate = 6
            continue yyl
        }
      case 20:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 58
              return .waiting
            }
            yystate = 6
            continue yyl
          default:
            self.yycursor += 1
            yystate = 17
            continue yyl
        }
      case 21:
        self.yystate = yycmedia_type
#sourceLocation(file: "advanced.re", line: 114)
        return .end
#sourceLocation(file: "advanced.swift", line: 623)
      case 22:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 59
              return .waiting
            }
            self.yycursor += 1
            yystate = 23
            continue yyl
          case 0x0D:
            self.yytm1 = self.add(tag: self.yytm1, value: self.yycursor)
            self.yycursor += 1
            yystate = 25
            continue yyl
          default:
            self.yycursor += 1
            yystate = 26
            continue yyl
        }
      case 23:
        yystate = 24
        continue yyl
      case 24:
        self.yystate = yycheader
#sourceLocation(file: "advanced.re", line: 115)
        return .error
#sourceLocation(file: "advanced.swift", line: 658)
      case 25:
        self.yyaccept = 0
        self.yymarker = self.yycursor
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x0A:
            self.yycursor += 1
            yystate = 27
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 60
              return .waiting
            }
            yystate = 24
            continue yyl
        }
      case 26:
        self.yyaccept = 0
        self.yymarker = self.yycursor
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 61
              return .waiting
            }
            yystate = 24
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 29
            continue yyl
          case 0x0D:
            self.yytm1 = self.add(tag: self.yytm1, value: self.yycursor)
            self.yycursor += 1
            yystate = 30
            continue yyl
          default:
            self.yycursor += 1
            yystate = 31
            continue yyl
        }
      case 27:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 32
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 62
              return .waiting
            }
            yystate = 28
            continue yyl
        }
      case 28:
        self.yycursor = self.yymarker
        if self.yyaccept == 0 {
          yystate = 24
          continue yyl
        } else {
          yystate = 37
          continue yyl
        }
      case 29:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 63
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 29
            continue yyl
          case 0x20:
            self.yycursor += 1
            yystate = 31
            continue yyl
          default:
            self.yycursor += 1
            yystate = 33
            continue yyl
        }
      case 30:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x0A:
            self.yycursor += 1
            yystate = 27
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 64
              return .waiting
            }
            yystate = 28
            continue yyl
        }
      case 31:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 65
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 29
            continue yyl
          case 0x0D:
            self.yytm1 = self.add(tag: self.yytm1, value: self.yycursor)
            self.yycursor += 1
            yystate = 30
            continue yyl
          default:
            self.yycursor += 1
            yystate = 31
            continue yyl
        }
      case 32:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 66
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 32
            continue yyl
          case 0x0D:
            self.yytm3 = self.add(tag: self.yytm3, value: self.yycursor)
            self.yytm2 = self.yytm1
            self.yytm2 = self.add(tag: self.yytm2, value: self.yycursor)
            self.yycursor += 1
            yystate = 34
            continue yyl
          default:
            self.yytm3 = self.add(tag: self.yytm3, value: self.yycursor)
            self.yycursor += 1
            yystate = 35
            continue yyl
        }
      case 33:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 67
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x0D:
            self.yytm1 = self.add(tag: self.yytm1, value: self.yycursor)
            self.yycursor += 1
            yystate = 30
            continue yyl
          default:
            self.yycursor += 1
            yystate = 31
            continue yyl
        }
      case 34:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x0A:
            self.yycursor += 1
            yystate = 36
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 68
              return .waiting
            }
            yystate = 28
            continue yyl
        }
      case 35:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 69
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 38
            continue yyl
          case 0x0D:
            self.yytm2 = self.yytm1
            self.yytm2 = self.add(tag: self.yytm2, value: self.yycursor)
            self.yycursor += 1
            yystate = 34
            continue yyl
          default:
            self.yycursor += 1
            yystate = 35
            continue yyl
        }
      case 36:
        self.yyaccept = 1
        self.yymarker = self.yycursor
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yytm1 = self.yytm2
            self.yycursor += 1
            yystate = 32
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 70
              return .waiting
            }
            yystate = 37
            continue yyl
        }
      case 37:
        f1 = self.yytm1
        f2 = self.yytm3
        self.yystate = yycheader
#sourceLocation(file: "advanced.re", line: 103)
        
        var foldStart = f1, foldEnd = f2
        while foldStart != nil {
          log("\t\(getString(foldStart!.elem..<foldEnd!.elem))")
          foldStart = foldStart!.prev
          foldEnd   = foldEnd!.prev
        }

        return .done

#sourceLocation(file: "advanced.swift", line: 958)
      case 38:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 71
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 38
            continue yyl
          case 0x0D:
            self.yycursor += 1
            yystate = 39
            continue yyl
          case 0x20:
            self.yycursor += 1
            yystate = 35
            continue yyl
          default:
            self.yycursor += 1
            yystate = 40
            continue yyl
        }
      case 39:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x0A:
            self.yycursor += 1
            yystate = 41
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 72
              return .waiting
            }
            yystate = 28
            continue yyl
        }
      case 40:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x00:
            fallthrough
          case 0x01...0x08:
            fallthrough
          case 0x0A...0x0C:
            fallthrough
          case 0x0E...0x1E:
            fallthrough
          case 0x7F:
            if self.yylimit <= self.yycursor {
              self.yystate = 73
              return .waiting
            }
            yystate = 28
            continue yyl
          case 0x09:
            self.yycursor += 1
            yystate = 42
            continue yyl
          case 0x0D:
            self.yytm2 = self.yytm1
            self.yytm2 = self.add(tag: self.yytm2, value: self.yycursor)
            self.yycursor += 1
            yystate = 34
            continue yyl
          default:
            self.yycursor += 1
            yystate = 35
            continue yyl
        }
      case 41:
        yystate = 37
        continue yyl
      case 42:
        yych = self.buffer[self.yycursor]
        switch yych {
          case 0x09:
            fallthrough
          case 0x20:
            self.yycursor += 1
            yystate = 42
            continue yyl
          case 0x0D:
            self.yycursor += 1
            yystate = 39
            continue yyl
          default:
            if self.yylimit <= self.yycursor {
              self.yystate = 74
              return .waiting
            }
            yystate = 28
            continue yyl
        }
      case 43:
        self.yystate = yycheader
#sourceLocation(file: "advanced.re", line: 114)
        return .end
#sourceLocation(file: "advanced.swift", line: 1070)
      case 44:
        if self.yylimit <= self.yycursor {
          yystate = 21
          continue yyl
        }
        yystate = 0
        continue yyl
      case 45:
        if self.yylimit <= self.yycursor {
          yystate = 2
          continue yyl
        }
        yystate = 3
        continue yyl
      case 46:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 4
        continue yyl
      case 47:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 7
        continue yyl
      case 48:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 8
        continue yyl
      case 49:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 10
        continue yyl
      case 50:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 11
        continue yyl
      case 51:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 12
        continue yyl
      case 52:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 14
        continue yyl
      case 53:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 15
        continue yyl
      case 54:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 16
        continue yyl
      case 55:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 17
        continue yyl
      case 56:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 18
        continue yyl
      case 57:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 19
        continue yyl
      case 58:
        if self.yylimit <= self.yycursor {
          yystate = 6
          continue yyl
        }
        yystate = 20
        continue yyl
      case 59:
        if self.yylimit <= self.yycursor {
          yystate = 43
          continue yyl
        }
        yystate = 22
        continue yyl
      case 60:
        if self.yylimit <= self.yycursor {
          yystate = 24
          continue yyl
        }
        yystate = 25
        continue yyl
      case 61:
        if self.yylimit <= self.yycursor {
          yystate = 24
          continue yyl
        }
        yystate = 26
        continue yyl
      case 62:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 27
        continue yyl
      case 63:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 29
        continue yyl
      case 64:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 30
        continue yyl
      case 65:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 31
        continue yyl
      case 66:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 32
        continue yyl
      case 67:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 33
        continue yyl
      case 68:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 34
        continue yyl
      case 69:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 35
        continue yyl
      case 70:
        if self.yylimit <= self.yycursor {
          yystate = 37
          continue yyl
        }
        yystate = 36
        continue yyl
      case 71:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 38
        continue yyl
      case 72:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 39
        continue yyl
      case 73:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 40
        continue yyl
      case 74:
        if self.yylimit <= self.yycursor {
          yystate = 28
          continue yyl
        }
        yystate = 42
        continue yyl
      default: fatalError("internal lexer error")
    }
  }
#sourceLocation(file: "advanced.re", line: 116)

  }

  // Feed the next data packet into the buffer
  mutating func feed(string: StaticString) -> Bool {
    let shift = self.token
    let free = Self.bufferSize - (self.yylimit - shift)

    return string.withUTF8Buffer { chunk in
      // Error: no free space, in the real world we can reallocate a larger buffer.
      if (free < chunk.count) {
        log("Token too long for receive buffer:", self.buffer.count)
        return false
      }

      if (shift > 0) {
        // Shift buffer contents, discarding already processed data.
        self.buffer.replaceSubrange(..<(Self.bufferSize - shift), with: self.buffer[shift..<Self.bufferSize])
        self.yylimit  -= shift
        self.yycursor -= shift
        self.yymarker -= shift
        self.token = 0
        
#sourceLocation(file: "advanced.swift", line: 1315)
        if self.yyt1 != Self.tagNone { self.yyt1 -= shift }
        if self.yyt2 != Self.tagNone { self.yyt2 -= shift }
#sourceLocation(file: "advanced.re", line: 138)

      }

      // Fill remaining space with new data.
      self.buffer.replaceSubrange(self.yylimit..<(self.yylimit + chunk.count), with: chunk)
      self.yylimit += chunk.count

      return true
    }
  }

  // Append a single value to an m-tag history.
  private mutating func add(tag prevTag: MTag?, value: Int) -> MTag {
    let tag = MTag(prev: prevTag, element: value)
    self.mTagPool.append(tag)
    return tag
  }

  // Decode a string from a slice of the buffer.
  private func getString(_ range: Range<Int>) -> String {
    String(data: Data(self.buffer[range]), encoding: .utf8)!
  }

  enum Status {
    case waiting
    case done
    case end
    case error
  }
}

// An m-tag tree is a way to store histories with an O(1) copy operation.
// Histories naturally form a tree, as they have a common start and fork
// at some point. The tree is stored as an array of pairs (tag value,
// link to parent). An m-tag is represented with a single index in the tree.
class MTag {
  weak var prev: MTag?
  var elem: Int

  init(prev: MTag?, element: Int) {
    self.prev = prev
    self.elem = element
  }
}

func test(packets: [StaticString]) -> Int32 {
  var c = State()

  // Main loop. The buffer contains incomplete data which appears packet by
  // packet. When the lexer needs more input it saves its internal state and
  // returns to the caller which should provide more input and resume lexing.
  var chunkIdx = 0
  finally: while true {
    switch (c.parse()) {
      case .waiting:
        print("waiting")
        guard c.feed(string: packets[chunkIdx]) else {
          return 1
        }
        chunkIdx += 1
      case .done:
        print("done")
      case .end:
        print("end")
        break finally
      case .error:
        print("error")
        return 1
    }
  }
  return 0
}

@main struct Program {
  static func main() {
    let packets: [StaticString] = [
      "ap",
      "plication/j",
      "son;",
      " charset=\"",
      "utf\\\"-8\"\r",
      "\n",
      ""
    ];

    let code = test(packets: packets)
    if code != 0 {
      log("Error exit:", code)
    }
    exit(code)
  }
}
