/* Generated by re2swift */
// re2swift $INPUT -o $OUTPUT -i --header lexer/state.swift



extension LexerState {
  mutating func lex() -> Int {
  let t: Int
  
  var yych: UInt8 = 0
  var yystate: UInt = 0
  yyl: while true {
    switch yystate {
      case 0:
        yych = str[cur]
        switch yych {
          case 0x61:
            cur += 1
            yystate = 0
            continue yyl
          case 0x62:
            self.yyt1 = cur
            cur += 1
            yystate = 2
            continue yyl
          default:
            self.yyt1 = cur
            yystate = 1
            continue yyl
        }
      case 1:
        t = self.yyt1
        return t
      case 2:
        yych = str[cur]
        switch yych {
          case 0x62:
            cur += 1
            yystate = 2
            continue yyl
          default:
            yystate = 1
            continue yyl
        }
      default: fatalError("internal lexer error")
    }
  }

  }
}

@main struct Program {
  static func main() {
    let str: StaticString = "ab"
    var state = LexerState(str: str.utf8Start, cur: 0)
    assert(state.lex() == 1)
  }
}
