/* Generated by re2swift */

public struct LexerState {
  public var str: UnsafePointer<UInt8>
  public var cur: Int
  public var yyt1 = -1

  public init(str: UnsafePointer<UInt8>, cur: Int = 0) {
    self.str = str
    self.cur = cur
  }
}
