/* Generated by re2swift */
#sourceLocation(file: "include.re", line: 1)
// re2swift $INPUT -o $OUTPUT --api simple

#sourceLocation(file: "definitions.swift", line: 1)
enum Result { case ok, fail }

#sourceLocation(file: "definitions.swift", line: 5)

#sourceLocation(file: "include.re", line: 3)


func lex(_ yyinput: UnsafePointer<UInt8>) -> Result {
  var yycursor = 0, yymarker = 0
  
#sourceLocation(file: "include.swift", line: 17)
  var yych: UInt8 = 0
  var yyaccept: UInt = 0
  var yystate: UInt = 0
  while true {
    switch yystate {
      case 0:
        yych = yyinput[yycursor]
        yycursor += 1
        switch yych {
          case 0x2E:
            yystate = 3
            continue
          case 0x30:
            yystate = 4
            continue
          case 0x31...0x39:
            yystate = 5
            continue
          default:
            yystate = 1
            continue
        }
      case 1:
        yystate = 2
        continue
      case 2:
#sourceLocation(file: "include.re", line: 10)
        return .fail
#sourceLocation(file: "include.swift", line: 46)
      case 3:
        yych = yyinput[yycursor]
        switch yych {
          case 0x30...0x39:
            yycursor += 1
            yystate = 7
            continue
          default:
            yystate = 2
            continue
        }
      case 4:
        yyaccept = 0
        yymarker = yycursor
        yych = yyinput[yycursor]
        switch yych {
          case 0x2E:
            yycursor += 1
            yystate = 7
            continue
          case 0x30...0x39:
            yycursor += 1
            yystate = 9
            continue
          case 0x45:
            fallthrough
          case 0x65:
            yycursor += 1
            yystate = 11
            continue
          default:
            yystate = 2
            continue
        }
      case 5:
        yyaccept = 1
        yymarker = yycursor
        yych = yyinput[yycursor]
        switch yych {
          case 0x2E:
            yycursor += 1
            yystate = 7
            continue
          case 0x30...0x39:
            yycursor += 1
            yystate = 5
            continue
          case 0x45:
            fallthrough
          case 0x65:
            yycursor += 1
            yystate = 11
            continue
          default:
            yystate = 6
            continue
        }
      case 6:
#sourceLocation(file: "include.re", line: 11)
        return .ok
#sourceLocation(file: "include.swift", line: 107)
      case 7:
        yyaccept = 2
        yymarker = yycursor
        yych = yyinput[yycursor]
        switch yych {
          case 0x30...0x39:
            yycursor += 1
            yystate = 7
            continue
          case 0x45:
            fallthrough
          case 0x65:
            yycursor += 1
            yystate = 11
            continue
          default:
            yystate = 8
            continue
        }
      case 8:
#sourceLocation(file: "extra_rules.re.inc", line: 6)
        return .ok
#sourceLocation(file: "include.swift", line: 130)
      case 9:
        yych = yyinput[yycursor]
        switch yych {
          case 0x2E:
            yycursor += 1
            yystate = 7
            continue
          case 0x30...0x39:
            yycursor += 1
            yystate = 9
            continue
          case 0x45:
            fallthrough
          case 0x65:
            yycursor += 1
            yystate = 11
            continue
          default:
            yystate = 10
            continue
        }
      case 10:
        yycursor = yymarker
        switch yyaccept {
          case 0:
            yystate = 2
            continue
          case 1:
            yystate = 6
            continue
          default:
            yystate = 8
            continue
        }
      case 11:
        yych = yyinput[yycursor]
        switch yych {
          case 0x2B:
            fallthrough
          case 0x2D:
            yycursor += 1
            yystate = 12
            continue
          case 0x30...0x39:
            yycursor += 1
            yystate = 13
            continue
          default:
            yystate = 10
            continue
        }
      case 12:
        yych = yyinput[yycursor]
        switch yych {
          case 0x30...0x39:
            yycursor += 1
            yystate = 13
            continue
          default:
            yystate = 10
            continue
        }
      case 13:
        yych = yyinput[yycursor]
        switch yych {
          case 0x30...0x39:
            yycursor += 1
            yystate = 13
            continue
          default:
            yystate = 8
            continue
        }
      default: fatalError("internal lexer error")
    }
  }
#sourceLocation(file: "include.re", line: 13)

}

assert(lex("123") == .ok)
assert(lex("123.4567") == .ok)
