#!/bin/sh

root_dir=$(pwd)

for f in $(find . -name '*.re'); do
    cd $(dirname $f)

    swiftfile="$(basename ${f%.re}.swift)"
    swifttest="example.swift"

    [ -f "$swiftfile" ] || { echo "\"$swiftfile\" doesn't exist"; exit 1; }

    cat "$swiftfile" \
        | grep -E -v "warning: rule .*matches empty string \[-Wmatch-empty-string\]" \
        | grep -E -v 'warning: tag .* degree of nondeterminism \[-Wnondeterministic-tags\]' \
        > "$swifttest"

    # If the autogenerated message appears more than once in the file, then
    # it must have autogenerated header appended at the end. Cut it off.
    msg='Generated by re2swift'
    if [ $(grep -c "$msg" "$swifttest") -gt 1 ]; then
        # Get the line of the second message occurrence.
        l=$(grep -n "$msg" "$swifttest" | tail -n +2 | cut -d : -f 1)
        # Cut off everything past that line.
        head -n $l "$swifttest" > "$swifttest".mod && mv "$swifttest".mod "$swifttest"
    fi

    extra_args="-g"
    echo "${f#'./'}"

    # Header test needs to build an extra module
    mod_dir=""
    mod=""
    header=$(grep -Eo -- '--header [^ ]+' "$swifttest")
    if [ "$?" -eq 0 ]; then
        header=$(echo "$header" | sed -E 's/--header ([^ ]*).*/\1/')
        header_src=$(basename "$header")
        mod_dir=$(dirname "$header")
        mod=${mod_dir##*/}
        cd $mod_dir
        swiftc $extra_args -emit-module -emit-library -static -module-name $mod "$header_src" || { echo "*** error ***"; exit 1; }
        extra_args="$extra_args -L$mod_dir -I$mod_dir -l$mod"
        cd "$root_dir/$(dirname $f)"
    fi

    swiftc $extra_args -o example "$swifttest" && ./example 2>/dev/null || { echo "*** error ***"; exit 1; }

    # Clean up build artifacts.
    if [ -n "$mod" ]; then
        rm -f "$mod_dir/lib$mod.a"
        for ext in o abi.json swiftdoc swiftmodule swiftsourceinfo; do rm -f "$mod_dir/$mod.$ext"; done
    fi
    rm -f "$swifttest" example
    [ -d "example.dSYM" ] && rm -r example.dSYM
    cd $root_dir
done

echo "All good."
